name: "Flexlate After-Conflict Action"
description: "Official Flexlate Github Action to be used after resolving merge conflict PRs"
inputs:
  branch_name:
    required: false
    description: "The flexlate-templates branch name that was used in resolving the merge conflict. Defaults to the branch name of the PR."
  gh_token:
    required: true
    description: "The Github token to use for authentication"
runs:
  using: composite
  steps:
    - name: Get branch name
      id: get_branch_name
      shell: bash
      run: |
        if [ -z "$PASSED_BRANCH_NAME" ]; then
          if [[ "$MERGED_BRANCH_NAME" = flexlate-templates-* ]]; then
            # Remove flexlate-templates- prefix
            branch_suffix="${MERGED_BRANCH_NAME#flexlate-templates-}"
            # Remove -for-conflicts suffix
            base_branch="${branch_suffix%-for-conflicts}"
            echo ::set-output name=use_branch::$base_branch;
            echo ::set-output name=is_flexlate_branch::true;
            echo "Using base branch: $base_branch"
          else
            echo "$MERGED_BRANCH_NAME is not a flexlate-templates branch"
            echo ::set-output name=is_flexlate_branch::false;
          fi
        else
          echo ::set-output name=is_flexlate_branch::true;
          echo ::set-output name=use_branch::$PASSED_BRANCH_NAME;
          echo "Using passed branch name: $PASSED_BRANCH_NAME"
        fi;
      env:
        MERGED_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        PASSED_BRANCH_NAME: ${{ inputs.branch_name }}
    - name: Merge Flexlate Output Branch into Feature Branch
      if: steps.get_branch_name.outputs.is_flexlate_branch
      uses: devmasx/merge-branch@1.4.0
      with:
        type: now
        from_branch: flexlate-output-${{ steps.get_branch_name.outputs.use_branch }}
        target_branch: ${{ steps.get_branch_name.outputs.use_branch }}
        github_token: ${{ github.token }}
    - name: Create PR with template update
      if: steps.get_branch_name.outputs.is_flexlate_branch
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ steps.get_branch_name.outputs.use_branch }}
        pr_title: Update project templates using Flexlate
        pr_body: |
          Update template using Flexlate.

          Before merging, review the changes and adjust manually if necessary.
        pr_label: "no auto merge,automated pr"
        github_token: ${{ inputs.gh_token }}
